# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


parameters:
  - name: GHCR_USER
    type: string
  - name: GHCR_PASSWORD
    type: string
    
trigger:
- main
- develop

pool:
  vmImage: ubuntu-latest

steps:
  - task: Maven@3
    displayName: Package
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 1.11
      jdkArchitectureOption: x64
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
  - bash: echo $(GHCR_USER) 
  - task: Maven@3
    displayName: Build Docker Image
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'spring-boot:build-image'
      publishJUnitResults: false
      jdkVersionOption: 1.11
  
